### ISSUE TITLE
Installation error on windows by shelljs

### ISSUE THREAD

**Issue by basarat** [travs/atom-package-dependencies#6]
Error details: 
`
UTF-8JavaScriptmaster1
node_modules\atom-package-dependencies\index.js98,1
Uncaught Error: EBADF, bad file descriptor` 

Reason: shelljs has the following in `exec.js`: 

```js
  c.stdout.on('data', function(data) {
    output += data;
    if (!options.silent)
      process.stdout.write(data);
  });
```

For whatever reason `process.stdout` is invalid. I suspect this is simply an issue with changes in how atom hosts processes so it might be failing on linux as well now. Recommended fix: add `options.silent`.

**Comment by travs** [comment]
Hey thanks for the report! :beetle: 

Let me know if the package behaves properly in atom!

**Comment by basarat** [comment]
>Let me know if the package behaves properly in atom! 

beautifully for now!
